### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by ritvik7** [shurcooL/github_flavored_markdown#2]
I want to use [Sourcegraph](https://sourcegraph.com) for github_flavored_markdown code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/shurcooL/github_flavored_markdown. (It should only take 30 seconds.)

Thank you!

**Comment by shurcooL** [comment]
This is done now. :)
