### ISSUE TITLE
Mr Dimitri

### ISSUE THREAD

**Issue by CloudHaze** [shurcooL/github_flavored_markdown#21]
Hey mr dimitri please back to this forum where you used to help people with their monitors
You are amazing ^^
https://hardforum.com/members/shurcool.168917/

**Comment by dmitshur** [comment]
Hi there. Thanks for the compliment.

If you're interested in the topic of LCD monitors, I'd suggest you check out https://www.testufo.com/ and https://www.blurbusters.com/ websites, as well as follow their author on Twitter at https://twitter.com/BlurBusters. There is some very interesting and useful content there. Enjoy!
