### ISSUE TITLE
possibly bug, definite weirdness

### ISSUE THREAD

**Issue by iansmith** [shurcooL/github_flavored_markdown#23]
Dmitri: I use velvet(github.com/gobuffalo/velvet) for some things and just (perhaps today, maybe yesterday) started seeing the output below.  Note also the weird "shurcoo!l"  ... (maybe that's go doing it because of the capital L in shurcooL?)...  I looked at the commits and didn't see any changes recently to your package, nor do I see any changes to black friday since mid-april.... so I frankly have no bloody idea what is going on....

```
$ go get -u github.com/gobuffalo/velvet
go: finding github.com/gobuffalo/velvet latest
# github.com/shurcooL/github_flavored_markdown
../go/pkg/mod/github.com/shurcoo!l/github_flavored_markdown@v0.0.0-20181002035957-2122de532470/main.go:71:7: const initializer blackfriday.EXTENSION_NO_INTRA_EMPHASIS | blackfriday.EXTENSION_TABLES | blackfriday.EXTENSION_FENCED_CODE | blackfriday.EXTENSION_AUTOLINK | blackfriday.EXTENSION_STRIKETHROUGH | blackfriday.EXTENSION_SPACE_HEADERS | blackfriday.EXTENSION_NO_EMPTY_LINE_BEFORE_BLOCK is not a constant
../go/pkg/mod/github.com/shurcoo!l/github_flavored_markdown@v0.0.0-20181002035957-2122de532470/main.go:71:20: undefined: blackfriday.EXTENSION_NO_INTRA_EMPHASIS
../go/pkg/mod/github.com/shurcoo!l/github_flavored_markdown@v0.0.0-20181002035957-2122de532470/main.go:72:2: undefined: blackfriday.EXTENSION_TABLES
../go/pkg/mod/github.com/shurcoo!l/github_flavored_markdown@v0.0.0-20181002035957-2122de532470/main.go:73:2: undefined: blackfriday.EXTENSION_FENCED_CODE
../go/pkg/mod/github.com/shurcoo!l/github_flavored_markdown@v0.0.0-20181002035957-2122de532470/main.go:74:2: undefined: blackfriday.EXTENSION_AUTOLINK
../go/pkg/mod/github.com/shurcoo!l/github_flavored_markdown@v0.0.0-20181002035957-2122de532470/main.go:75:2: undefined: blackfriday.EXTENSION_STRIKETHROUGH
../go/pkg/mod/github.com/shurcoo!l/github_flavored_markdown@v0.0.0-20181002035957-2122de532470/main.go:76:2: undefined: blackfriday.EXTENSION_SPACE_HEADERS
../go/pkg/mod/github.com/shurcoo!l/github_flavored_markdown@v0.0.0-20181002035957-2122de532470/main.go:77:2: undefined: blackfriday.EXTENSION_NO_EMPTY_LINE_BEFORE_BLOCK
../go/pkg/mod/github.com/shurcoo!l/github_flavored_markdown@v0.0.0-20181002035957-2122de532470/main.go:93:2: undefined: blackfriday.Html
```

I don't know if this on your side or somebody else, but thought that you might want to know.

**Comment by iansmith** [comment]
After some scratching around I found out there are two versions of the black friday code by russ ross.

```
$ cat go.sum|grep black
github.com/russross/blackfriday v1.5.2 h1:HyvC0ARfnZBqnXwABFeSZHpKvJHJJfPz81GNueLj0oo=
github.com/russross/blackfriday v1.5.2/go.mod h1:JO/DiYxRf+HjHt06OyowR9PTA263kcR/rfWxYHBV53g=
github.com/russross/blackfriday v2.0.0+incompatible h1:cBXrhZNUf9C+La9/YpS+UHpUT8YD6Td9ZMSU9APFcsk=
github.com/russross/blackfriday v2.0.0+incompatible/go.mod h1:JO/DiYxRf+HjHt06OyowR9PTA263kcR/rfWxYHBV53g=
```

and I expect that Velvet didn't pin their dependencies to 1.5.2

**Comment by dmitshur** [comment]
This package requires v1 of `github.com/russross/blackfriday` package. Unfortunately, there's a bad v2.0.0 tag in the blackfriday which results in a v2.0.0+incompatible version of v1 blackfriday API.

As a result, if you ever do `go get -u` on `github.com/shurcooL/github_flavored_markdown` or a package that imports it, you may end upgrading blackfriday to an incompatible v2.0.0+incompatible version.

In the future, you should probably do something like this instead:

```
go get github.com/gobuffalo/velvet@latest
```

Instead of using `-u`, which tries to aggressively update all dependencies.

This is similar to https://github.com/shurcooL/markdownfmt/issues/47#issuecomment-475998549.
