### ISSUE TITLE
where are examples?

### ISSUE THREAD

**Issue by d-rep** [shurcooL/github_flavored_markdown#24]
README.md says "See examples for how to generate a complete HTML page, including CSS styles."  Where are examples?

**Comment by dmitshur** [comment]
The examples are part of the documentation of the package.

You can view documentation for Go packages on websites like [godoc.org](https://godoc.org) and [pkg.go.dev](https://pkg.go.dev), or locally via the [`golang.org/x/tools/cmd/godoc`](https://golang.org/x/tools/cmd/godoc) tool.

There's a badge in the README that links to documentation:

[![GoDoc](https://godoc.org/github.com/shurcooL/github_flavored_markdown?status.svg)](https://godoc.org/github.com/shurcooL/github_flavored_markdown)

And the examples can be viewed there, see https://godoc.org/github.com/shurcooL/github_flavored_markdown#pkg-examples.

**Comment by d-rep** [comment]
Worked great, thanks @dmitshur for the details.
