### ISSUE TITLE
Anchors don't match GitHub anchor name

### ISSUE THREAD

**Issue by martine** [shurcooL/github_flavored_markdown#3]
From this markdown:
https://github.com/mbostock/d3/wiki/API-Reference

It has links like:
```
* [Behaviors](#d3behavior-behaviors) - reusable interaction behaviors
```

That are aimed at targets like:
```
## [d3.behavior (Behaviors)](Behaviors)
```

However, your library generates the above heading with HTML like the following, so the anchor doesn't line up.
```
<h2><a name="a-href-behaviors-d3-behavior-behaviors-a" class="anchor" href="#a-href-behaviors-d3-behavior-behaviors-a" rel="nofollow" aria-hidden="true"><span class="octicon octicon-link"></span></a>
```

**Comment by shurcooL** [comment]
This is a valid bug. Thank you for reporting it!

I'll fix it.
