### ISSUE TITLE
Heading links aren't linkified (due to blockquote perhaps?)

### ISSUE THREAD

**Issue by martine** [shurcooL/github_flavored_markdown#4]
This page:
https://github.com/mbostock/d3/wiki/Selections
opens with:
```
 > [Wiki](Home) ▸ [[API Reference]] ▸ [[Core]] ▸ **Selections**
```

which doesn't get its links linked, instead rendering as

```
<blockquote>
<p><a href="Home" rel="nofollow">Wiki</a> ▸ [[API Reference]] ▸ [[Core]] ▸ <strong>Selections</strong></p>
</blockquote>
```

**Comment by shurcooL** [comment]
I think this is working as intended.

You linked to a wiki page, which uses special syntax. In normal GitHub Flavored Markdown, `[[Text]]` in double brackets like that doesn't mean anything.

You can confirm this yourself by using GitHub's own [Markdown rendering API](https://developer.github.com/v3/markdown/#render-a-markdown-document-in-raw-mode):

```
$ curl -X POST -H'Content-Type: text/x-markdown' https://api.github.com/markdown/raw -d'> [Wiki](Home) ▸ [[API Reference]] ▸ [[Core]] ▸ **Selections**'
<blockquote>
<p><a href="Home">Wiki</a> ▸ [[API Reference]] ▸ [[Core]] ▸ <strong>Selections</strong></p>
</blockquote>
```

Which is identical to the output of this package, except the `rel="nofollow"`.

**Comment by shurcooL** [comment]
@martine, do you agree?

**Comment by martine** [comment]
Yes, it does.  I didn't realize that github wikis do not use github flavored markdown.

Do you happen to have any advice on how I might render a github wiki to HTML?  Using your library gets me pretty close.  I guess I can parse the wikitext ahead of time rewriting `[[foo]]` into `[foo](foo)` and then pass it to markdown?
