### ISSUE TITLE
Lists following paragraphs

### ISSUE THREAD

**Issue by AdamColton** [shurcooL/github_flavored_markdown#9]
If a list follows a paragraph without a blank line, it does not correctly parse the list

This will not render correctly
```
Some text
- A
- B
- C
```

This will

```
Some text

- A
- B
- C
```

**Comment by shurcooL** [comment]
Hi, thanks for reporting this.

I can confirm that GitHub's markdown parser will interpret the first input without a blank line as a paragraph and list, but the blackfriday v1 parser that this library uses does not. At least not with the options I'm using.

Does the Markdown specification (loosely speaking, but we can look at CommonMark for a proper specification) say anything about the blank line being optional?

**Comment by AdamColton** [comment]
I'm not sure what the spec says, but that is the behavior on GitHub.

Here's an example in one of my repos: https://github.com/AdamColton/packeter/blob/master/readme.md

**Comment by shurcooL** [comment]
Sorry for the delay. I've gotten around to investigating this, and I have a fix. It turned out to be quite short. There's a flag that controls this behavior in Blackfriday, and we need to use it to match GitHub Flavored Markdown rendering.

Thanks again for reporting the issue @AdamColton!
